name: Update README ⭐
on:
  schedule:
        - cron: '30 9 1-25 12 *'                      # from the 1. December till 25. December every day at 9:30am (avoid load at full hours)
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: $$ { secrets.AOC_USER_ID }}
          sessionCookie: ${{ secrets.AOC_SESSION }}
      - uses: stefanzweifel/git-auto-commit-action@v5 # use v5
        with:
          commit_message: Update README stars
